# Generated by Django 4.1.1 on 2022-09-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorInnfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('markName', models.CharField(max_length=50)),
                ('model', models.IntegerField(max_length=20)),
                ('factoryInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.factorinnfo')),
            ],
        ),
    ]
