# Generated by Django 4.1.1 on 2022-09-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='FactorInnfo',
            new_name='FactorInformation',
        ),
    ]
