# Generated by Django 4.1.1 on 2022-09-23 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_cars_car_rename_factorinnfo_factorinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 23, 5, 42, 27, 745004, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
