# Generated by Django 4.1.1 on 2022-09-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='NotSet', max_length=50)),
                ('lname', models.CharField(default='NotSet', max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('student_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.track')),
            ],
        ),
    ]
