# Generated by Django 4.1.1 on 2022-09-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_exams_alter_student_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
